language: python
env:
  matrix:
    - TOXENV=emacs23
    - TOXENV=emacs24
    - TOXENV=emacs-snapshot
matrix:
  allow_failures:
    - env: TOXENV=emacs-snapshot
    - env: TOXENV=emacs23
before_install:
  - pip install --quiet --use-mirrors tox
  - if [ "$TOXENV" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - if [ "$TOXENV" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
script:
  - VIRTUAL_ENV= tox
after_failure:
  - cat elpa/install.log
  - cat .tox/$TOXENV/log/*.log
