language: python
python: 2.7
dist: trusty
sudo: false
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-26.2-travis
  - EVM_EMACS=emacs-26.3-travis
  - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - pip install -q Flask==1.0.2 tornado==5.1.1
  - pip uninstall -y Werkzeug
  - pip install -q Werkzeug==0.14.1
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - make before-test
script:
  - emacs --version
  - make test
